@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueApplicationList
UniqueApplicationList -right-> "*" Application

Application *--> Company
Application *--> Role
Application *--> ApplicationDate
Application *--> "0..1" Url
Application *--> Status
@enduml
